# Generated by Django 5.2.6 on 2026-09-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('controle_dettes_bloquant', models.BooleanField(default=True, help_text='Si coché, un ticket du jour payé avec dettes antérieures n’est pas considéré en règle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marches', to='marches.commune')),
            ],
            options={
                'ordering': ['commune__nom', 'nom'],
                'unique_together': {('commune', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='PenaliteParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fixe', models.PositiveIntegerField(default=0, help_text='GNF')),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('majoration_par_jour', models.PositiveIntegerField(default=0, help_text='Majoration quotidienne après clôture (0 = désactivée).')),
                ('marche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalite', to='marches.marche')),
            ],
        ),
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('est_deambulant', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_place', to='marches.marche')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('marche', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(help_text='Montant en GNF')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='marches.typeplace')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
