# Generated by Django 5.2.6 on 2026-09-24 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0002_commune_suppression_demandee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='suppression_demandee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marche',
            name='suppression_demandee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches_a_supprimer', to=settings.AUTH_USER_MODEL),
        ),
    ]
