# Generated by Django 5.2.6 on 2026-09-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone Orange Money')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='commercants/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercants_crees', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercants', to='marches.marche')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_commercant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commerçant',
                'verbose_name_plural': 'commerçants',
                'ordering': ['nom'],
                'unique_together': {('marche', 'telephone')},
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fixe', 'Place fixe'), ('deambulant', 'Déambulant')], default='fixe', max_length=20)),
                ('code', models.CharField(help_text='Numéro de boutique / table, ou code déambulant', max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='recensement.commercant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_crees', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='marches.marche')),
                ('type_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='marches.typeplace')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('marche', 'code')},
            },
        ),
    ]
