# Generated by Django 5.2.6 on 2026-09-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marches', '0001_initial'),
        ('recensement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('objet', models.CharField(blank=True, max_length=80)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('montant', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec'), ('timeout', 'Timeout')], default='en_attente', max_length=16)),
                ('mock_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='recensement.commercant')),
                ('initiateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_inities', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='marches.marche')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=40, unique=True)),
                ('signature', models.CharField(editable=False, max_length=16)),
                ('date_validite', models.DateField()),
                ('montant', models.PositiveIntegerField()),
                ('montant_penalite', models.PositiveIntegerField(default=0)),
                ('majoration', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('emis', 'Émis'), ('en_attente_paiement', 'En attente de paiement'), ('paye', 'Payé'), ('controle', 'Contrôlé'), ('impaye', 'Impayé'), ('regularise', 'Régularisé'), ('annule', 'Annulé'), ('expire', 'Expiré')], default='emis', max_length=24)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('motif_annulation', models.TextField(blank=True)),
                ('controle_at', models.DateTimeField(blank=True, null=True)),
                ('penalite_annulee', models.BooleanField(default=False)),
                ('motif_annulation_penalite', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_annules', to=settings.AUTH_USER_MODEL)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='recensement.commercant')),
                ('controleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_controles', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_emis', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='marches.marche')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='recensement.place')),
                ('type_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='marches.typeplace')),
            ],
            options={
                'ordering': ['-date_validite', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_affecte', models.PositiveIntegerField()),
                ('statut_precedent', models.CharField(choices=[('emis', 'Émis'), ('en_attente_paiement', 'En attente de paiement'), ('paye', 'Payé'), ('controle', 'Contrôlé'), ('impaye', 'Impayé'), ('regularise', 'Régularisé'), ('annule', 'Annulé'), ('expire', 'Expiré')], max_length=24)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='tickets.paiement')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_paiement', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ClotureJournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tickets_emis', models.PositiveIntegerField(default=0)),
                ('tickets_payes', models.PositiveIntegerField(default=0)),
                ('tickets_impayes', models.PositiveIntegerField(default=0)),
                ('tickets_regularises', models.PositiveIntegerField(default=0)),
                ('tickets_annules', models.PositiveIntegerField(default=0)),
                ('penalites_emises', models.PositiveIntegerField(default=0)),
                ('penalites_encaissees', models.PositiveIntegerField(default=0)),
                ('montant_tarifs_payes', models.PositiveIntegerField(default=0)),
                ('montant_om', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to='marches.marche')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('marche', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date_validite', 'statut'], name='tickets_tic_date_va_c1dec7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numero'], name='tickets_tic_numero_061d5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paiementligne',
            unique_together={('paiement', 'ticket')},
        ),
    ]
